Last edited: 1/28/2026, 3:38 PM CST
# Table of climate models and members that we use

In [3]:
# import base packages for data analysis
import pandas as pd

from evt_heat_waves.config import DATA_ROOT, CONFIG_PATH
from evt_heat_waves.mip_fit.cmip_dataclass import CMIP6EnsembleConfig

In [4]:
CMIPConfig = CMIP6EnsembleConfig.from_yaml(
    CONFIG_PATH.parent / 'meta.yaml',
    CONFIG_PATH.parent /  'qc.yaml'
)

AMIPConfig = CMIP6EnsembleConfig.from_yaml(
    CONFIG_PATH.parent / 'meta_amip.yaml',
    CONFIG_PATH.parent / 'qc_amip.yaml'
)

In [5]:
rows = []
rows_amip = []

for m in CMIPConfig.iter_active_models('tas_annual_max'):
    tmp_prim_mem = m.primary_member
    prim_mem = tmp_prim_mem.split("_")[1]

    rows.append({
        "Model": m.name,
        "Variables": "tas_annual_max, tas_annual_mean",
        "Primary Member": prim_mem,
        "Time Interval": "1979-2024",
        "Experiment": "historical + SSP5-8.5"
    })

for m in AMIPConfig.iter_active_models('tas_annual_max'):
    tmp_prim_mem = m.primary_member
    prim_mem = tmp_prim_mem.split("_")[1]

    rows_amip.append({
        "Model": m.name,
        "Variables": "tas_annual_max, tas_annual_mean",
        "Primary Member": prim_mem,
        "Time Interval": "1979-2024",
        "Experiment": "historical + SSP5-8.5"
    })

In [9]:
df = pd.DataFrame(rows)
df_amip = pd.DataFrame(rows_amip)
df_amip.sort_values("Model")

,Model,Variables,Primary Member,Time Interval,Experiment
0,ACCESS-CM2,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
1,ACCESS-ESM1-5,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5
2,AWI-CM-1-1-MR,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
3,AWI-ESM-1-1-LR,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
4,BCC-ESM1,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
5,CAMS-CSM1-0,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
6,CESM2-FV2,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
7,CESM2-WACCM-FV2,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
8,CMCC-CM2-HR4,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
9,CMCC-CM2-SR5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
10,CMCC-ESM2,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
11,CNRM-CM6-1-HR,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
12,CNRM-ESM2-1,"tas_annual_max, tas_annual_mean",r10i1p1f2,1979-2024,historical + SSP5-8.5
13,CanESM5,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5
14,EC-Earth3-AerChem,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
15,EC-Earth3-CC,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
16,EC-Earth3-Veg-LR,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
17,FGOALS-f3-L,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
18,GFDL-CM4,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
19,GFDL-ESM4,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
20,HadGEM3-GC31-LL,"tas_annual_max, tas_annual_mean",r1i1p1f3,1979-2024,historical + SSP5-8.5
21,HadGEM3-GC31-MM,"tas_annual_max, tas_annual_mean",r1i1p1f3,1979-2024,historical + SSP5-8.5
22,IITM-ESM,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
23,INM-CM4-8,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
24,INM-CM5-0,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5
25,IPSL-CM5A2-INCA,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
26,KACE-1-0-G,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
27,KIOST-ESM,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
28,MIROC6,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5
29,MPI-ESM-1-2-HAM,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
30,MPI-ESM1-2-HR,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5
31,MPI-ESM1-2-LR,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5
32,MRI-ESM2-0,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
33,NorESM2-LM,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
34,SAM0-UNICON,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
35,TaiESM1,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5

In [8]:
df.sort_values("Model")

,Model,Variables,Primary Member,Time Interval,Experiment
0,AWI-CM-1-1-MR,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
1,BCC-CSM2-MR,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
2,CAMS-CSM1-0,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
3,CESM2-WACCM,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
4,CMCC-CM2-SR5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
5,CMCC-ESM2,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
6,CNRM-CM6-1-HR,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
7,CNRM-ESM2-1,"tas_annual_max, tas_annual_mean",r10i1p1f2,1979-2024,historical + SSP5-8.5
8,EC-Earth3-CC,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
9,EC-Earth3-Veg,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5
10,EC-Earth3-Veg-LR,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
11,FGOALS-g3,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
12,GFDL-CM4,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
13,GFDL-ESM4,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
14,HadGEM3-GC31-LL,"tas_annual_max, tas_annual_mean",r1i1p1f3,1979-2024,historical + SSP5-8.5
15,HadGEM3-GC31-MM,"tas_annual_max, tas_annual_mean",r1i1p1f3,1979-2024,historical + SSP5-8.5
16,IITM-ESM,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
17,INM-CM4-8,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
18,INM-CM5-0,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5
19,KACE-1-0-G,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
20,KIOST-ESM,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
21,MIROC-ES2L,"tas_annual_max, tas_annual_mean",r1i1p1f2,1979-2024,historical + SSP5-8.5
22,MIROC6,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5
23,MPI-ESM1-2-HR,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5
24,MPI-ESM1-2-LR,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5
25,NorCPM1,"tas_annual_max, tas_annual_mean",r2i1p1f1,1979-2024,historical + SSP5-8.5
26,NorESM2-LM,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
27,TaiESM1,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
28,UKESM1-0-LL,"tas_annual_max, tas_annual_mean",r10i1p1f2,1979-2024,historical + SSP5-8.5

In [13]:
pd.merge(df, df_amip, on='Model', how='outer').fillna('N/A').sort_values("Model")

,Model,Variables_x,Primary Member_x,Time Interval_x,Experiment_x,Variables_y,Primary Member_y,Time Interval_y,Experiment_y
29,ACCESS-CM2,N/A,N/A,N/A,N/A,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
30,ACCESS-ESM1-5,N/A,N/A,N/A,N/A,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5
0,AWI-CM-1-1-MR,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
31,AWI-ESM-1-1-LR,N/A,N/A,N/A,N/A,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
1,BCC-CSM2-MR,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,N/A,N/A,N/A,N/A
32,BCC-ESM1,N/A,N/A,N/A,N/A,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
2,CAMS-CSM1-0,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
33,CESM2-FV2,N/A,N/A,N/A,N/A,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
3,CESM2-WACCM,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,N/A,N/A,N/A,N/A
34,CESM2-WACCM-FV2,N/A,N/A,N/A,N/A,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
35,CMCC-CM2-HR4,N/A,N/A,N/A,N/A,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
4,CMCC-CM2-SR5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
5,CMCC-ESM2,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
6,CNRM-CM6-1-HR,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
7,CNRM-ESM2-1,"tas_annual_max, tas_annual_mean",r10i1p1f2,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r10i1p1f2,1979-2024,historical + SSP5-8.5
36,CanESM5,N/A,N/A,N/A,N/A,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5
37,EC-Earth3-AerChem,N/A,N/A,N/A,N/A,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
8,EC-Earth3-CC,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
9,EC-Earth3-Veg,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5,N/A,N/A,N/A,N/A
10,EC-Earth3-Veg-LR,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
38,FGOALS-f3-L,N/A,N/A,N/A,N/A,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
11,FGOALS-g3,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,N/A,N/A,N/A,N/A
12,GFDL-CM4,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
13,GFDL-ESM4,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
14,HadGEM3-GC31-LL,"tas_annual_max, tas_annual_mean",r1i1p1f3,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r1i1p1f3,1979-2024,historical + SSP5-8.5
15,HadGEM3-GC31-MM,"tas_annual_max, tas_annual_mean",r1i1p1f3,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r1i1p1f3,1979-2024,historical + SSP5-8.5
16,IITM-ESM,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
17,INM-CM4-8,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
18,INM-CM5-0,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5
39,IPSL-CM5A2-INCA,N/A,N/A,N/A,N/A,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
19,KACE-1-0-G,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
20,KIOST-ESM,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
21,MIROC-ES2L,"tas_annual_max, tas_annual_mean",r1i1p1f2,1979-2024,historical + SSP5-8.5,N/A,N/A,N/A,N/A
22,MIROC6,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5
40,MPI-ESM-1-2-HAM,N/A,N/A,N/A,N/A,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
23,MPI-ESM1-2-HR,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5
24,MPI-ESM1-2-LR,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r10i1p1f1,1979-2024,historical + SSP5-8.5
41,MRI-ESM2-0,N/A,N/A,N/A,N/A,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
25,NorCPM1,"tas_annual_max, tas_annual_mean",r2i1p1f1,1979-2024,historical + SSP5-8.5,N/A,N/A,N/A,N/A
26,NorESM2-LM,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
42,SAM0-UNICON,N/A,N/A,N/A,N/A,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
27,TaiESM1,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5,"tas_annual_max, tas_annual_mean",r1i1p1f1,1979-2024,historical + SSP5-8.5
28,UKESM1-0-LL,"tas_annual_max, tas_annual_mean",r10i1p1f2,1979-2024,historical + SSP5-8.5,N/A,N/A,N/A,N/A

In [11]:
df.to_csv(
    DATA_ROOT / 'CMIP6' / 'supplemental_info' / 'model_var_primmem_time_exp.csv',
    index=False
)

df_amip.to_csv(
    DATA_ROOT / 'AMIP' / 'supplemental_info' / 'model_var_primmem_time_exp.csv',
    index=False
)